# Generated by Django 4.2.2 on 2023-06-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_alter_post_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
